### PR TITLE
[MRG] PR to make the SGE install script more robust

### PR DESCRIPTION
**Pull request by ogrisel**
Add some debug information (e.g. qhost output) to understand what's going on.

### CODE REVIEW

**Comment by arjoly** [comment]
Do you think we should try to use docker for travis and local debugging?

**Comment by ogrisel** [comment]
> Do you think we should try to use docker for travis and local debugging

This is precisely what I did. It works on my local docker but similar configuration does not work on travis.

I will close this PR as the solution found by @kpetrov seems to work. We are rebasing his own PR to clean it up.

**Comment by ogrisel** [comment]
Ooops, I close the wrong PR, sorry.

**Comment by ogrisel** [comment]
@arjoly @kpetrov I amended the squashed commit with more cleanups. Do a `git pull --rebase` if you want to pull it locally.

I still want to experiment with removing some calls to `sleep` and `service gridengine-* restart` to speed up the setup. They are probably not necessary.

**Comment by ogrisel** [comment]
> set -xe

It enables both "local echo" (`-x`) to display the shell commands that are executed and the "exit on error" (`-e`) behavior for the rest of the bash script.

**Comment by ogrisel** [comment]
Ok I did some more clean up and squashing. I think this is ready for review. Have a look at the output of qhost and qstat in travis: there is no more error messages: the exechost seems to be registered properly.

**Comment by arjoly** [comment]
This looks good. Thanks a lot.

I intend to merge this whenever you answer to my last question.

**Comment by arjoly** [comment]
Can you add your name (and other relevant people ?) at the line ``Add a travis workers with SGE. By Arnaud Joly`` from the what's new?

**Comment by ogrisel** [comment]
> This files seems unused. Should we merge this in the install script?

It makes it easier to collect additional info from the SGE env on travis. It's not enabled by default because it's very verbose but can be useful to keep ready in case we encounter SGE configuration problems.

**Comment by arjoly** [comment]
Merge by rebase, I have added your name in the what's new. feel free to make pull request if more people have to be added in it.

**Comment by arjoly** [comment]
Thanks fort tout hard work!:beers:

**Pull request merged**
