### PR TITLE
[MRG] Uniform log accross scheduler + job id in log name

### PR DESCRIPTION
**Pull request by arjoly**
Superseeds https://github.com/clusterlib/clusterlib/pull/26

### CODE REVIEW

**Comment by arjoly** [comment]
@ogrisel This should be ready for a last look before squashing everything and merge it to master.

**Comment by arjoly** [comment]
@ogrisel I would like to merge this before the week end. If you don't have time to review, it's not a problem. Cheers!

**Comment by arjoly** [comment]
@ogrisel I will merge this in the evening. Furthermore, I have added some doc to fix https://github.com/clusterlib/clusterlib/issues/30

**Comment by arjoly** [comment]
merged :-) thanks @ogrisel

**Comment by ogrisel** [comment]
Thanks @arjoly. Sorry for the lack of feedback. I plan to resume work on clusterlib soon-ish.

**Pull request merged**
